- id: pre-plantuml
  name: PlantUML Diagram Generation Pre-Commit
  description: Generates SVGs of PlantUML diagrams found in path specified in arguments.
  entry: main
  language: golang
  types: [text]
  files: .+\.(pu)