- id: gardener
  name: PlantUML Diagram Generation Pre-Commit
  description: Generates SVGs of PlantUML diagrams found in path specified in arguments.
  entry: gardener
  language: golang
  types: [text]